config/routes.rb
Academia::Application.routes.draw do
  
  resources :materials
  
  get "pages/home"

  get "pages/about"

  get "pages/contact"

  root :to => 'pages#home'

end

app/models/material.rb
class Material < ActiveRecord::Base
  attr_accessible :title, :description, :publication_date, :issue, :year, :pages, :pdf
  
  url_regex =  /(^$)|(^(http|https):\/\/[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$)/ix
     
  validates :title, :presence => true
  validates :description, :presence => true
  
  has_attached_file :pdf
  
  validates_attachment_presence :pdf
  
end

app/models/publisher.rb
class Publisher < ActiveRecord::Base
  attr_accessible :name, :city  
  
  validates :name, :presence => true
  validates :city, :presence => true
  
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/materials_controller.rb
class MaterialsController < ApplicationController
  def index
    @materials = Material.all
  end
  
  def show    
    @material = Material.find_by_id(params[:id])
    if @material.nil?
      flash[:error] = "The material you ordered was not found!"
      redirect_to :action => :index
    else    
      @title = @material.title
    end
  end
  
  def new
    @material = Material.new
    @title = "New Material"
  end
  
  def create
    @material = Material.create(params[:material])
    if @material.valid?
      flash[:success] =  "Material created successfully!"
      redirect_to @material
    else
      @title = "New Material"
      render "new" 
    end
  end
  
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @title = "Home"
    @materials = Material.all
  end

  def about
    @title = "About"
  end

  def contact
    @title = "Contact"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/materials_helper.rb
module MaterialsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Academia | <%= @title %></title>
	  <!--[if lt IE 9]>
	<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
	<![endif]-->    
	<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
	<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
	<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
	
	<%= stylesheet_link_tag 'custom', :media => 'screen' %>
	


  <%= csrf_meta_tags %>
  
</head>
<body>
<div class="container">	
	<div class ="span-17">
		<nav class="round" style = "margin-top: 1em;">
		  <ul>
		    <li><%= link_to "Home", pages_home_path %></li>
		    <li><%= link_to "About", pages_about_path %></li>
		    <li><%= link_to "Contact", pages_contact_path %></li>
		  </ul>
		</nav>
	</div>
	
<header class="span-17 round ">
    <div class="span-3">           
      <%= image_tag("rickvanderzwet_mortarboard.png.jpeg", :width => 100 ,:alt => "Sample App", :class => "round") %>				
    </div>    
    <div class="span-13" id="text-header">  
	 	<h1>Academia</h1>
	 	<p>a simple rails app to manage your academic papers</p>
    </div>
</header>
<div class="span-17">
	<section class="round">
		<% flash.each do |key, value| %>
		<div class="flash <%= key %>"><%= value %></div>
		<% end %>
		<%= yield %>
	</section>		
</div>
<div class="span-17">
	<footer>
	  <nav class=" round">
	    <ul>
	      <li><%= link_to "About", '#' %></li>
	      <li><%= link_to "Contact", '#' %></li>
	      <li><a href="http://news.railstutorial.org/">News</a></li>
	      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
	    </ul>
	  </nav>
	</footer>
</div>
<div class="span-17 last">
	<div class="box round" style="margin-top: 1em;">		
	<%= debug(params) if Rails.env.development? %>
	</div>
</div>
</body>
</html>

app/views/materials/_material.html.erb
<p><b><%= link_to material.title, material %></b></p>
<p><%= material.description %></p>

app/views/materials/index.html.erb
<h1>All the materials!</h1>
<hr />
<%= render @materials %>

app/views/materials/new.html.erb
<h1>Add a new material!</h1>

<%= form_for(@material, :html => { :multipart => true }) do |f| %>
  <% if @material.errors.any? %>
  	<div id="error_explanation">
  	  <p><%= pluralize(@material.errors.count, "error") %> prohibited from saving this material:</p>  
  	  <ul>
  	  <% @material.errors.full_messages.each do |msg| %>
  	  	<li><%= msg %></li>
  	  <% end %>
  	  </ul>  	  	
  	</div>  	
  <% end %>
  	
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>  
  <div class="text">
  	<%= f.label :description%><br />
  	<%= f.text_area :description %>
  </div>
  <div class="field">
  	<%= f.file_field :pdf %>
  </div>
  
    <div class="actions">
  	<%= f.submit %>
  </div>
<% end %>

app/views/materials/show.html.erb
<h1><%= @material.title %></h1>
<p>Published: <%= @material.publication_date %></p>

<p><%= @material.description %></p>

<p><%= link_to "Download", @material.pdf.url %></p>

app/views/pages/about.html.erb
<h1>About</h1>
<p>Here you can find more about me</p>

app/views/pages/contact.html.erb
<h1>Contact</h1>
<p>Welcome to the contact page</p>

app/views/pages/home.html.erb
<h1>Home</h1>
<p>Welcome to the Academia app home page!</p>
<p>Click <%= link_to "here", materials_path %> to view all materials on this website</p>